### ISSUE TITLE
Facing an issue while executing the code

### ISSUE THREAD

**Issue by srinivasrao3812** [sajjadkarimi91/P300-BCI#1]
Hi sir,
I am Srinivas presently started working on BCI related to P300, saw your code and tried to execute but getting error which i could not resolve so can you please give some suggestions so that i would be able to execute the given code.

Thanks a lot for uploading an informative work Sajjad Karimi

![WhatsApp Image 2022-09-01 at 21 04 26](https://user-images.githubusercontent.com/112719520/188201520-0f94b2f3-a9b3-4f01-a3f8-0c936c643000.jpeg)

**Comment by sajjadkarimi91** [comment]
Hi Srinivas 
I updated the repository. 
To make the required data, you can set preprocess_flag to 1 at the first run in LINE 10.
preprocess_flag = 1; % 0 for skipping preprocessing & epoching step

Thank for your point

**Comment by srinivasrao3812** [comment]
Thanks a lot sir for your prompt response,

After making the changes suggested by you, but still i am having errors, Need your help to resolve this problem sir
![Uploading WhatsApp Image 2022-09-03 at 22.05.54.jpeg…]()

**Comment by sajjadkarimi91** [comment]
Hi
I could not see the image; please send it again or paste the error text.

**Comment by srinivasrao3812** [comment]
Hi sir, I have attached the error that i am getting, please help me in running this code

Error using extracttrials
Too many input arguments.

Error in p300_classifiers (line 41)
            extracttrials(load_path,save_path, new_sampling_rate);

![image](https://user-images.githubusercontent.com/112719520/188483026-8a9923b9-f69c-4778-bb8e-89eb7e0ac650.png)

**Comment by sajjadkarimi91** [comment]
Ok, I got it.
You must unzip the dataset without extracting its code (**crossvalidate.m** and **extracttrials.m**).
To avoid this condition in the future, I renamed the function and committed it again in GitHub.
Please download the last version.
It is recommended that you create a /dataset folder for the EPFL dataset without any new and extra codes like the below image.


![image](https://user-images.githubusercontent.com/50092872/188486735-a59e8616-2b50-4f8d-ba7a-1405a5ce5f00.png)

**Comment by srinivasrao3812** [comment]
ok sir thanks a lot I will download and try once again.

I have observed that in the data set provided 
https://www.epfl.ch/labs/mmspg/research/page-58317-en-html/bci-2/bci_datasets/
does not contain subject 5

Sir can you suggest some good papers to relate with this work?

Can I apply a different data set to the code will it work?

**Comment by sajjadkarimi91** [comment]
Yes, the dataset excludes one subject due to noisy recording.

You could study new deep learning papers for P300 classification, such as
  Deep learning based on batch normalization for P300 signal detection
  Single-trial P300 classification using convolutional LSTM and deep learning ensembles method

These codes can also be applied to other P300 classifications by modifying the loading data parts and the final aggregation of classifier outputs.

**Comment by srinivasrao3812** [comment]
thanks a lot sir
